### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by malhar2460** [MSTC-DA-IICT/Hacktoberfest24-Mushroom-Edibility-Prediction-ML#2]
## Objective
The objective of this issue is to Visualize the data, and provide the conclusions after each process, identify the patterns among the data which can help in improving our model, suggest what feature engineering can be done.

## Tasks
- Data Visualization, provide as much graphs as possible, and also provide conclusions after each process.
- Identify the patterns among the data.
- Conduct statistical analysis on the dataset to uncover relationships between variables.
- Suggest what feature engineering can be done on the data.

### The code should be well commented explaining the reason behind steps where necessary.

**Comment by Abhicoder03** [comment]
@malhar2460 Hey I find this issue interesting. I want to work on this. Will you please assign this to me.

**Comment by nirmalshah20519** [comment]
I have done  Exploratory data analysis on the given dataset and Raised a PR for the same
Kindly check and merge the same.

**Comment by venilv912** [comment]
@nirmalshah20519 You are assigned the task of EDA.

**Comment by nirmalshah20519** [comment]
@venilv912 Thanks for assigning the task to me.
I have updated and raised the PR request. Kindly check and merge the same.

**Comment by shyamsaktawat** [comment]
Hi @venilv912,

I find this issue intriguing and would love to contribute! Could you please assign me the task? I’ll focus on visualizing the dataset, identifying key patterns, conducting statistical analysis, and suggesting potential feature engineering improvements.

I’ll ensure to provide detailed graphs, well-commented code, and conclusions after each process as outlined in the task description.

Looking forward to your confirmation!
