### ISSUE TITLE
Model Implementation

### ISSUE THREAD

**Issue by malhar2460** [MSTC-DA-IICT/Hacktoberfest24-Mushroom-Edibility-Prediction-ML#3]
## Objective
Implement the following Classification Models for classification of whether the ***'mushroom'*** is ***'poisonous'*** or ***'edible'***.

## Tasks
- Data Cleaning & Transformation, encoding categorial data which has to be used in the model.
- Implement the below given models of Classification.

## Models
- Logistic Regression
- K Nearest Neighbours
- Random Forest
- Support Vector Classifier

### The code should be well commented explaining the reason behind steps where necessary.

**Comment by Abhicoder03** [comment]
@malhar2460 Hey I find this issue interesting. I want to work on this. Will you please assign this to me.

**Comment by venilv912** [comment]
@Abhicoder03 You can work on this issue, you have to implement any one of the models, which model are you going to implement?

**Comment by eric157** [comment]
hi @malhar2460 @venilv912 

I've submitted a pull request implementing Logistic Regression, KNN, Random Forest, and SVC models for the Mushroom Classification project. 
The key features include:
Feature Engineering: Applied categorical encoding and interaction features.
Hyperparameter Tuning: GridSearchCV across all models.
Results: Achieved precision, recall, and f1-score of 1.00 on both training and test sets.
The code is well-documented. Please review and merge if it meets the requirements.

Thanks!

**Comment by venilv912** [comment]
@eric157 You can work on this issue, you have to implement KNN and SVC only and make sure to commit the file in a separate directory named `Classification Models`.

**Comment by eric157** [comment]
@venilv912 Kindly check my latest commit `Classification Model 01`. I have implemented KNN and SVC, and the file is now located in the updated directory named `Classification Models` (previously 'Classification-Models')
